version: '3.5'

services:
    app:
        build: ./docker/images/php81
        volumes:
            - ./application:/var/www/html
        ports:
            - "8080:8000"
        links:
            - postgresql
        working_dir: /var/www/html
    postgresql:
        image: postgres:14.1-alpine
        ports:
            - "5425:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: pQLkm8NOkS088x
            POSTGRES_DB: bb-lms
        volumes:
            - ./docker/images/postgres/files/postgresql.conf:/etc/postgresql.conf
        command: [ "postgres", "-c", "config_file=/etc/postgresql.conf" ]
        restart: always



